spring:
  kafka:
    producer:
      properties:
        interceptor.classes: ""

  data:
    redis:
      repositories:
        enabled: false
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
      - org.springframework.boot.autoconfigure.data.redis.RedisRepositoriesAutoConfiguration

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

management:
  tracing:
    enabled: false
  zipkin:
    tracing:
      export:
        enabled: false
  endpoints:
    enabled-by-default: false

docflow:
  security:
    jwt:
      secret: dGVzdC1zZWNyZXQta2V5LWF0LWxlYXN0LTMyLWJ5dGVzLWxvbmctZm9yLWhtYWMtc2hh

app:
  admin:
    username: admin
    password: admin123